name: devmicro

services:
    mysqldb:
        container_name: mysqldb
        image: "mysql:8.0"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            TZ: America/Guayaquil
            MYSQL_DATABASE: microdev
            MYSQL_ROOT_PASSWORD: rootroot
            MYSQL_USER: devel_one
            MYSQL_PASSWORD: devel_one
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            interval: 10s
            timeout: 20s
            retries: 10
    micropc:
        container_name: micropc
        build:
            context: micro_person_client
            dockerfile: Dockerfile
        image: micro_person_client:latest
        ports:
            - "8080:8080"
        environment:
            - spring.datasource.url=jdbc:mysql://mysqldb:3306/microdev
        depends_on:
            mysqldb:
                condition: service_healthy
    microat:
        container_name: microat
        build:
            context: micro_account_tx
            dockerfile: Dockerfile
        image: micro_account_tx:latest
        ports:
            - "8081:8081"
        environment:
            - spring.datasource.url=jdbc:mysql://mysqldb:3306/microdev
        depends_on:
            mysqldb:
                condition: service_healthy
