FROM alpine/java:22-jdk
MAINTAINER vizuete.eduardo@gmail.com
COPY target/micro_person_client-0.0.1-SNAPSHOT.jar micro_person_client-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/micro_person_client-0.0.1-SNAPSHOT.jar"]